name: SquadronDirector
main: io.github.cccm5.SquadronDirectorMain
version: ${project.version}
api-version: 1.13
depend: [Movecraft]
commands:
    squadrondirector:
        description: Main command for squadron director
        aliases:
            - sd
            - sdir
            - sdirector
permissions:
    Squadron.sign.release:
        description: Allows users to release their squadron with a sign
    Squadron.sign.launch:
        description: Allows users to enter launching mode with a sign
    Squadron.sign.cruise:
        description: Allows users to set cruising with a sign
    Squadron.sign.rotate:
        description: Allows users to rotate with a sign
    Squadron.sign.lever:
        description: Allows users to activate levers with a sign
    Squadron.sign.button:
        description: Allows users to activate buttons with a sign
    Squadron.sign.torp:
        description: Allows users to launch torps with a sign
    Squadron.sign.recon:
        description: Allows users to see their squadron from a recon view
    Squadron.sign.formup:
        description: Allows users to form up with a sign
    Squadron.sign.remote:
        description: Allows users to use a remote sign on their squadron

    Squadron.command.release:
        description: Allows users to release their squadron with a command
    Squadron.command.scuttle:
        description: Allows users to scuttle their squadron with a command
    Squadron.command.launch:
        description: Allows users to enter launching mode with a command
    Squadron.command.cruise:
        description: Allows users to set cruising with a command
    Squadron.command.rotate:
        description: Allows users to rotate with a command
    Squadron.command.lever:
        description: Allows users to activate levers with a command
    Squadron.command.button:
        description: Allows users to activate buttons with a command
    Squadron.command.formup:
        description: Allows users to form up with a command

    Squadron.craftname:
        description: Allows users to direct a craft named craftnamed
